version: '3.8'

services:
  rag-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-chatbot-container
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - GEMINI_API_KEY
      - MOCK_EMBEDDINGS
      - JWT_SECRET_KEY
      - JWT_ALGORITHM
      - RETRIEVAL_THRESHOLD
      - ALLOWED_ORIGINS
      - CHROMA_DB_PATH
      - SQLITE_DB_PATH
      - PORT
      - HOST
    restart: unless-stopped
